# Generated by Django 6.1 on 2026-09-02 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Project Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('location', models.CharField(default='Jubilee Hills, Hyderabad', max_length=150)),
                ('project_type', models.CharField(default='3BHK Flat Renovation', max_length=120)),
                ('client_type', models.CharField(default='Private Homeowner', max_length=100)),
                ('project_status', models.CharField(choices=[('completed', 'Completed'), ('ongoing', 'Under Execution'), ('upcoming', 'Upcoming / Planning')], default='completed', max_length=20)),
                ('duration', models.CharField(default='3 Months', max_length=50)),
                ('built_up_area', models.CharField(default='2,400 sq.ft', max_length=50)),
                ('overview', models.TextField()),
                ('scope_of_work', models.TextField(blank=True)),
                ('challenges', models.TextField(blank=True)),
                ('solutions', models.TextField(blank=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('before_image', models.ImageField(blank=True, null=True, upload_to='projects/before/')),
                ('after_image', models.ImageField(blank=True, null=True, upload_to='projects/after/')),
                ('featured', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.projectcategory')),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
