# Generated by Django 6.1 on 2026-09-02 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='actual_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='contract_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total Agreed Project Value in ₹', max_digits=14),
        ),
        migrations.AddField(
            model_name='project',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='project',
            name='customer_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='project',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='customer_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='expected_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total Cleared Payments in ₹', max_digits=14),
        ),
        migrations.AddField(
            model_name='project',
            name='progress_percentage',
            field=models.PositiveIntegerField(default=0, help_text='0 to 100%'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(choices=[('planning', 'Planning & Permits'), ('ready_to_start', 'Ready to Start'), ('ongoing', 'Under Execution / In Progress'), ('near_completion', 'Near Completion / Finishing'), ('completed', 'Completed & Handed Over'), ('on_hold', 'On Hold'), ('delayed', 'Delayed')], default='completed', max_length=30),
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('contract', 'Signed Contract / Agreement'), ('drawing', 'Architectural / Structural 2D/3D Drawing'), ('approval', 'Municipal Building Permit / Sanction / NOC'), ('boq', 'Detailed Bill of Quantities (BOQ)'), ('report', 'Site Audit / Soil Investigation Report'), ('material_test', 'Concrete Cube / Steel Quality Test Certificate'), ('invoice', 'Commercial Tax Invoice'), ('handover', 'Handover Certificate & Snag Checklist'), ('other', 'Other Document')], default='other', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='projects/documents/%Y/%m/')),
                ('visibility', models.CharField(choices=[('ADMIN_ONLY', 'Admin & Superuser Only'), ('STAFF', 'Internal Staff & Engineers'), ('CUSTOMER', 'Shared with Customer in Portal'), ('PUBLIC', 'Publicly Accessible')], default='CUSTOMER', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project Document',
                'verbose_name_plural': 'Project Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('site_prep', 'Site Preparation & Clearance'), ('demolition', 'Demolition & Dismantling'), ('foundation', 'Soil Investigation & Foundation RCC'), ('structure', 'RCC Columns, Beams & Slabs'), ('brickwork', 'Brickwork & Masonry'), ('plumbing_mep', 'Plumbing, Drainage & Sanitary (MEP)'), ('electrical', 'Electrical Conduiting & Distribution'), ('plastering', 'Internal / External Plastering & Waterproofing'), ('flooring', 'Tiling & Flooring'), ('painting', 'Putty, Primer & Painting'), ('woodwork', 'Doors, Windows & Woodwork'), ('inspection', 'Civil & Quality Inspection'), ('handover', 'Final Handover & Snag Rectification')], default='structure', max_length=40)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Initiation'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('BLOCKED', 'Blocked / On Hold')], default='PENDING', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('progress_percentage', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Task',
                'verbose_name_plural': 'Project Tasks',
                'ordering': ['project', 'display_order', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(db_index=True, editable=False, max_length=40, unique=True)),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_phone', models.CharField(max_length=30)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('category', models.CharField(choices=[('project_progress', 'Project Execution / Progress Query'), ('billing_payment', 'Billing, Milestone & Payment Query'), ('site_inspection', 'Site Visit / Inspection Request'), ('quality_materials', 'Material Quality & Specifications'), ('general_inquiry', 'General Service Request')], default='project_progress', max_length=30)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open / New'), ('IN_PROGRESS', 'In Progress / Assigned'), ('WAITING_FOR_CUSTOMER', 'Waiting for Customer Response'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=25)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_tickets', to=settings.AUTH_USER_MODEL)),
                ('customer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='projects.project')),
            ],
            options={
                'verbose_name': 'Support Ticket',
                'verbose_name_plural': 'Support Tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='support/attachments/%Y/%m/')),
                ('is_staff_reply', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='projects.supportticket')),
            ],
            options={
                'verbose_name': 'Ticket Message',
                'verbose_name_plural': 'Ticket Messages',
                'ordering': ['created_at'],
            },
        ),
    ]
