# Generated by Django 6.1 on 2026-09-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('general', 'General'), ('construction', 'Construction'), ('renovation', 'Flat & Apartment Renovation'), ('demolition', 'Demolition & Site Services'), ('reconstruction', 'Reconstruction & Rebuilding'), ('redevelopment', 'Property Redevelopment'), ('nri', 'NRI Property Services'), ('finance', 'Construction & Renovation Loans')], default='general', max_length=30)),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_title', models.CharField(help_text='e.g. 3BHK Flat Owner, Jubilee Hills or NRI Property Investor, USA', max_length=150)),
                ('service_rendered', models.CharField(default='Complete Flat Renovation', max_length=100)),
                ('feedback', models.TextField()),
                ('rating', models.PositiveIntegerField(default=5)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('is_featured', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='BUILD+ Construction & Property Services', max_length=150)),
                ('tagline', models.CharField(default='Build Better. Renovate Smarter. Rebuild with Confidence.', max_length=255)),
                ('primary_phone', models.CharField(default='+91 98765 43210', max_length=50)),
                ('whatsapp_number', models.CharField(default='+91 98765 43210', max_length=50)),
                ('primary_email', models.EmailField(default='contact@buildplus.com', max_length=254)),
                ('office_address', models.TextField(default='Suite 402, Builders Tower, Financial District, Hyderabad, India')),
                ('facebook_url', models.URLField(blank=True, default='https://facebook.com')),
                ('instagram_url', models.URLField(blank=True, default='https://instagram.com')),
                ('linkedin_url', models.URLField(blank=True, default='https://linkedin.com')),
                ('years_experience', models.PositiveIntegerField(default=18)),
                ('projects_completed', models.PositiveIntegerField(default=450)),
                ('happy_clients', models.PositiveIntegerField(default=620)),
                ('service_cities', models.CharField(default='Hyderabad, Bangalore, Chennai, Vijayawada, Vizag', max_length=255)),
                ('meta_description', models.TextField(default='Premier construction, flat and apartment renovation, demolition, reconstruction, property redevelopment and NRI property management services.')),
                ('meta_keywords', models.CharField(default='construction, flat renovation, apartment renovation, demolition, reconstruction, redevelopment, NRI property services', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Website Settings',
                'verbose_name_plural': 'Website Settings',
            },
        ),
    ]
