# Generated by Django 6.1 on 2026-09-02 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of this category for SEO and public listings')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=15)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('author', models.CharField(default='BUILD+ Editorial Team', max_length=100)),
                ('short_description', models.TextField(help_text='Short summary displayed in blog listings and search results (max 500 chars)', max_length=500)),
                ('content', models.TextField(help_text='Main blog content with formatted HTML, headings, lists, quotes, and imagery')),
                ('featured_image', models.ImageField(blank=True, help_text='Hero image for public card listings and blog header (JPG, PNG, WebP)', null=True, upload_to='blog/%Y/%m/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=15)),
                ('featured', models.BooleanField(default=False, help_text='Check to display on the Home page Featured Insights carousel')),
                ('published_date', models.DateTimeField(blank=True, help_text='Date and time when article was published', null=True)),
                ('related_service_type', models.CharField(choices=[('flat_renovation', 'Flat & Apartment Renovation'), ('construction', 'New Construction (Houses & Villas)'), ('demolition', 'Building Demolition & Site Clearance'), ('reconstruction', 'Reconstruction & Rebuilding'), ('redevelopment', 'Property Redevelopment'), ('property_land', 'Property & Land Advisory'), ('nri_services', 'NRI Property Services'), ('construction_loan', 'Construction & Renovation Loans')], default='flat_renovation', help_text='Commercial service to link for contextual high-converting lead generation', max_length=40)),
                ('seo_title', models.CharField(blank=True, help_text='Custom SEO page title tag (defaults to blog title if empty)', max_length=180)),
                ('seo_description', models.CharField(blank=True, help_text='Custom meta description for search engines (defaults to short description)', max_length=255)),
                ('seo_keywords', models.CharField(blank=True, help_text='Comma-separated SEO keywords (e.g. flat renovation, old apartment repair)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Primary category for this article', on_delete=django.db.models.deletion.PROTECT, related_name='blogs', to='blog.blogcategory')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_date', '-created_at'],
            },
        ),
    ]
