# Generated by Django 6.1 on 2026-09-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_type', models.CharField(choices=[('construction', 'New Construction (House, Villa, Commercial)'), ('flat_renovation', 'Flat & Apartment Renovation'), ('apartment_renovation', 'Multi-Unit Apartment Renovation'), ('demolition', 'Building / Flat Demolition & Clearing'), ('reconstruction', 'Reconstruction & Rebuilding'), ('redevelopment', 'Property & Society Redevelopment'), ('property_land', 'Property & Land Advisory'), ('nri_services', 'NRI Property Support & Supervision'), ('construction_loan', 'Construction & Renovation Loan Assistance'), ('site_visit', 'Site Visit & Inspection Request')], default='flat_renovation', max_length=30)),
                ('full_name', models.CharField(max_length=120)),
                ('phone_number', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('city_location', models.CharField(help_text='e.g. Jubilee Hills, Hyderabad', max_length=150)),
                ('property_type', models.CharField(blank=True, help_text='e.g. 3BHK Resale Flat, G+2 Independent Building, Plot', max_length=100)),
                ('approximate_area', models.CharField(blank=True, help_text='e.g. 1,800 sq.ft or 300 sq.yds', max_length=60)),
                ('message', models.TextField(help_text='Describe your property requirement, existing condition, or project goals')),
                ('site_visit_requested', models.BooleanField(default=False)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NEW', 'New / Unread'), ('CONTACTED', 'Contacted / In Discussion'), ('SITE_VISIT', 'Site Visit Scheduled'), ('ESTIMATE', 'Estimate / BOQ Shared'), ('PROPOSAL', 'Proposal Under Review'), ('NEGOTIATION', 'In Negotiation'), ('CONVERTED', 'Converted to Active Project'), ('CLOSED', 'Closed / Not Feasible')], default='NEW', max_length=20)),
                ('internal_notes', models.TextField(blank=True, help_text='Internal notes for team and follow-up history')),
                ('assigned_engineer', models.CharField(blank=True, default='Unassigned', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Enquiry / Lead',
                'verbose_name_plural': 'Enquiries & Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
