# Generated by Django 6.1 on 2026-09-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='enquiry_number',
            field=models.CharField(blank=True, db_index=True, max_length=30, unique=True),
        ),
    ]
