# Generated by Django 6.1 on 2026-09-02 11:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIChatbotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, help_text='Master toggle for public AI chatbot')),
                ('ai_name', models.CharField(default='BUILD+ AI Consultant', max_length=100)),
                ('welcome_message', models.TextField(default="Hello! I'm your AI Construction & Property Consultant. How can I assist with your project today?")),
                ('business_description', models.TextField(default='BUILD+ specializes in Construction, Flat & Apartment Renovation, Demolition, Reconstruction, Society Redevelopment, Property/Land Due Diligence, and NRI Property Stewardship.')),
                ('contact_phone', models.CharField(default='+91 98765 43210', max_length=50)),
                ('whatsapp_number', models.CharField(default='+91 98765 43210', max_length=50)),
                ('working_hours', models.CharField(default='Mon - Sat: 9:00 AM - 7:30 PM IST', max_length=150)),
                ('emergency_message', models.TextField(default='For urgent site safety or structural concerns, please contact our senior engineering team directly via phone or WhatsApp.')),
                ('fallback_message', models.TextField(default="I apologize, but I couldn't process that. Would you like me to connect you with our engineering staff or help you submit an enquiry?")),
                ('human_handoff_message', models.TextField(default='I am connecting you with our senior customer consulting desk. A representative will take over or follow up with you shortly.')),
                ('enable_lead_capture', models.BooleanField(default=True)),
                ('enable_ai_summary', models.BooleanField(default=True)),
                ('enable_ai_priority', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Chatbot Settings',
                'verbose_name_plural': 'AI Chatbot Settings',
            },
        ),
        migrations.CreateModel(
            name='AIKnowledgeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('construction', 'New Construction (Houses, Villas, Commercial)'), ('renovation', 'Flat & Apartment Renovation (Resale, Damaged, Structural)'), ('demolition', 'Controlled Demolition & Site Clearance'), ('reconstruction', 'Structural Reconstruction & Rebuilding'), ('redevelopment', 'Property & Society Redevelopment'), ('property_land', 'Property & Land Advisory'), ('nri_services', 'NRI Property Stewardship & Supervision'), ('finance', 'Construction & Renovation Loans Guidance'), ('policy', 'Company Policies & Working Process')], db_index=True, max_length=40)),
                ('topic', models.CharField(help_text='e.g. 20-Year Old Resale Flat Plumbing Replacement', max_length=200)),
                ('keywords', models.CharField(help_text='Comma-separated trigger keywords (e.g. plumbing, GI pipes, leakage, seepage)', max_length=255)),
                ('approved_content', models.TextField(help_text='Factual, engineering-approved guidance for the AI to provide')),
                ('who_is_it_for', models.CharField(blank=True, help_text='e.g. Buyers of older apartments built before 2005', max_length=255)),
                ('typical_process', models.TextField(blank=True, help_text='Step-by-step engineering roadmap')),
                ('pricing_guideline', models.CharField(blank=True, help_text='Explain cost factors (never give fixed fake quotes)', max_length=255)),
                ('safety_boundary', models.CharField(blank=True, help_text='e.g. Must require on-site civil structural inspection', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Knowledge Snippet',
                'verbose_name_plural': 'AI Knowledge Base',
                'ordering': ['category', 'display_order', 'topic'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('visitor_name', models.CharField(blank=True, max_length=150)),
                ('visitor_phone', models.CharField(blank=True, max_length=50)),
                ('visitor_email', models.EmailField(blank=True, max_length=254)),
                ('visitor_whatsapp', models.CharField(blank=True, max_length=50)),
                ('visitor_location', models.CharField(blank=True, max_length=150)),
                ('service_category', models.CharField(blank=True, max_length=60)),
                ('service_type', models.CharField(blank=True, max_length=100)),
                ('property_type', models.CharField(blank=True, max_length=100)),
                ('property_condition', models.CharField(blank=True, max_length=100)),
                ('approximate_area', models.CharField(blank=True, max_length=100)),
                ('project_description', models.TextField(blank=True)),
                ('estimated_budget', models.CharField(blank=True, max_length=100)),
                ('timeline', models.CharField(blank=True, max_length=100)),
                ('is_nri', models.BooleanField(default=False)),
                ('site_visit_requested', models.BooleanField(default=False)),
                ('preferred_site_visit_date', models.DateField(blank=True, null=True)),
                ('detected_intent', models.CharField(blank=True, help_text='AI classified intent', max_length=150)),
                ('ai_lead_summary', models.TextField(blank=True, help_text='AI synthesized summary for sales team')),
                ('suggested_priority', models.CharField(choices=[('LOW', 'Low Priority'), ('MEDIUM', 'Medium Priority'), ('HIGH', 'High Priority'), ('URGENT', 'Urgent / Immediate Action')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active Conversation'), ('completed', 'Completed'), ('lead_created', 'Lead Converted'), ('human_handoff', 'Human Handoff Requested'), ('human_active', 'Human Agent Active'), ('abandoned', 'Abandoned / Idle'), ('closed', 'Closed')], db_index=True, default='active', max_length=30)),
                ('human_agent_active', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('assigned_human_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_chat_sessions', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_chat_sessions', to='crm.lead')),
            ],
            options={
                'verbose_name': 'AI Chat Session',
                'verbose_name_plural': 'AI Chat Sessions',
                'ordering': ['-last_activity_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('ai', 'AI Consultant'), ('user', 'Customer / Visitor'), ('human_agent', 'Staff Representative'), ('system', 'System Notice')], default='ai', max_length=20)),
                ('sender_name', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField()),
                ('quick_actions_json', models.JSONField(blank=True, default=list, help_text='Interactive button pills shown beneath AI message')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_assistant.chatsession')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['created_at'],
            },
        ),
    ]
