# Generated by Django 6.1 on 2026-09-02 07:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lead Source',
                'verbose_name_plural': 'Lead Sources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(db_index=True, editable=False, max_length=32, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(db_index=True, max_length=25)),
                ('alternate_phone', models.CharField(blank=True, max_length=25)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('whatsapp_number', models.CharField(blank=True, max_length=25)),
                ('preferred_contact_method', models.CharField(choices=[('phone', 'Phone Call'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('in_person', 'In-Person Meeting')], default='phone', max_length=20)),
                ('customer_type', models.CharField(choices=[('individual', 'Individual'), ('property_owner', 'Property Owner'), ('builder', 'Builder'), ('developer', 'Developer'), ('investor', 'Investor'), ('nri', 'NRI'), ('company', 'Company / Corporate'), ('agent', 'Agent / Broker'), ('other', 'Other')], default='individual', max_length=30)),
                ('service_category', models.CharField(choices=[('construction', 'Construction Services'), ('renovation', 'Flat & Apartment Renovation'), ('demolition', 'Demolition Services'), ('reconstruction', 'Reconstruction & Rebuilding'), ('redevelopment', 'Property Redevelopment'), ('property_land', 'Property & Land Advisory'), ('nri_services', 'NRI Property Services'), ('finance', 'Construction & Renovation Finance')], db_index=True, default='construction', max_length=40)),
                ('service_type', models.CharField(choices=[('independent_house_construction', 'Independent House Construction'), ('residential_construction', 'Residential Construction'), ('apartment_construction', 'Apartment Construction'), ('villa_construction', 'Villa Construction'), ('commercial_construction', 'Commercial Construction'), ('industrial_construction', 'Industrial / Structural Construction'), ('flat_renovation', 'Flat Renovation'), ('apartment_renovation', 'Apartment Renovation'), ('old_flat_renovation', 'Old Flat Renovation'), ('damaged_flat_renovation', 'Damaged Flat Renovation'), ('interior_renovation', 'Interior Renovation'), ('structural_renovation', 'Structural Renovation'), ('kitchen_renovation', 'Kitchen Renovation'), ('bathroom_renovation', 'Bathroom Renovation'), ('common_area_renovation', 'Common Area Renovation'), ('building_demolition', 'Building Demolition'), ('flat_demolition', 'Flat Demolition'), ('apartment_demolition', 'Apartment Demolition'), ('partial_demolition', 'Partial Demolition'), ('complete_demolition', 'Complete Demolition'), ('damaged_building_demolition', 'Damaged Building Demolition'), ('site_clearing', 'Site Clearing'), ('partial_reconstruction', 'Partial Reconstruction'), ('complete_reconstruction', 'Complete Reconstruction'), ('structural_reconstruction', 'Structural Reconstruction'), ('reconstruction_after_demolition', 'Reconstruction After Demolition'), ('property_redevelopment', 'Property Redevelopment'), ('apartment_redevelopment', 'Apartment Redevelopment'), ('old_building_redevelopment', 'Old Building Redevelopment'), ('multi_unit_redevelopment', 'Multi-Unit Redevelopment'), ('demolition_plus_reconstruction', 'Demolition + Reconstruction'), ('property_buying', 'Property Buying'), ('property_selling', 'Property Selling'), ('land_buying', 'Land Buying'), ('land_selling', 'Land Selling'), ('property_inspection', 'Property Inspection'), ('property_management', 'Property Management'), ('land_management', 'Land Management'), ('nri_property_management', 'NRI Property Management'), ('nri_land_management', 'NRI Land Management'), ('nri_property_inspection', 'NRI Property Inspection'), ('nri_construction_supervision', 'NRI Construction Supervision'), ('nri_renovation_supervision', 'NRI Renovation Supervision'), ('nri_demolition_supervision', 'NRI Demolition Supervision'), ('nri_reconstruction_supervision', 'NRI Reconstruction Supervision'), ('nri_property_buying', 'NRI Property Buying'), ('nri_property_selling', 'NRI Property Selling'), ('nri_documentation_assistance', 'NRI Documentation Assistance'), ('construction_loan', 'Construction Loan'), ('home_building_loan', 'Home / Building Loan'), ('renovation_finance', 'Renovation Finance'), ('property_finance', 'Property Finance'), ('loan_documentation', 'Loan Documentation')], db_index=True, default='residential_construction', max_length=60)),
                ('property_type', models.CharField(choices=[('independent_house', 'Independent House'), ('flat', 'Flat'), ('apartment', 'Apartment Building'), ('villa', 'Villa'), ('residential_building', 'Residential Building'), ('commercial_building', 'Commercial Building'), ('office', 'Office Space'), ('shop', 'Retail Shop / Showroom'), ('commercial_complex', 'Commercial Complex'), ('industrial_property', 'Industrial Property'), ('land', 'Plot / Land'), ('other', 'Other')], default='independent_house', max_length=40)),
                ('property_location', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(db_index=True, default='Hyderabad', max_length=100)),
                ('area_locality', models.CharField(blank=True, max_length=120)),
                ('approximate_property_area', models.CharField(blank=True, help_text='e.g. 2,400 sq.ft or 300 sq.yds', max_length=80)),
                ('unit', models.CharField(default='sq.ft', max_length=20)),
                ('project_description', models.TextField(blank=True)),
                ('estimated_budget', models.CharField(blank=True, help_text='Customer stated budget', max_length=100)),
                ('budget_range', models.CharField(blank=True, max_length=100)),
                ('expected_project_value', models.DecimalField(blank=True, decimal_places=2, help_text='Pipeline value in ₹', max_digits=14, null=True)),
                ('final_project_value', models.DecimalField(blank=True, decimal_places=2, help_text='Closed Won value in ₹', max_digits=14, null=True)),
                ('expected_closing_date', models.DateField(blank=True, null=True)),
                ('won_date', models.DateField(blank=True, null=True)),
                ('lost_reason', models.CharField(blank=True, choices=[('budget', 'Budget / Price too High'), ('competitor', 'Chosen Competitor'), ('cancelled', 'Customer Cancelled Project'), ('location', 'Location Outside Service Scope'), ('not_interested', 'Not Interested / Invalid Lead'), ('timeline', 'Timeline Mismatch'), ('unreachable', 'Could Not Contact / No Response'), ('duplicate', 'Duplicate Enquiry'), ('other', 'Other Reason')], max_length=40)),
                ('lost_notes', models.TextField(blank=True)),
                ('on_hold_reason', models.TextField(blank=True)),
                ('lead_source_text', models.CharField(blank=True, default='Website', max_length=100)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('QUALIFIED', 'Qualified'), ('SITE_VISIT', 'Site Visit'), ('REQUIREMENT_CONFIRMED', 'Requirement Confirmed'), ('ESTIMATE_PREPARED', 'Estimate Prepared'), ('PROPOSAL_SENT', 'Proposal Sent'), ('NEGOTIATION', 'Negotiation'), ('WON', 'Won'), ('LOST', 'Lost'), ('ON_HOLD', 'On Hold')], db_index=True, default='NEW', max_length=30)),
                ('next_follow_up_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_crm_leads', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_crm_leads', to=settings.AUTH_USER_MODEL)),
                ('lead_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.leadsource')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up_date', models.DateField()),
                ('follow_up_time', models.TimeField(blank=True, null=True)),
                ('follow_up_type', models.CharField(choices=[('phone', 'Phone Call'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('meeting', 'In-Person Meeting'), ('site_visit', 'Site Visit Follow-up'), ('video_call', 'Video Call'), ('other', 'Other')], default='phone', max_length=30)),
                ('subject', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('outcome', models.TextField(blank=True, help_text='What happened during communication')),
                ('next_follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_follow_ups', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='crm.lead')),
            ],
            options={
                'verbose_name': 'Follow-up',
                'verbose_name_plural': 'Follow-ups',
                'ordering': ['completed', 'follow_up_date', 'follow_up_time'],
            },
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimate_number', models.CharField(max_length=50, unique=True)),
                ('estimate_date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(help_text='e.g. 3BHK Turnkey Renovation BOQ Rev-1', max_length=255)),
                ('estimated_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Subtotal in ₹', max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='GST / Tax in ₹', max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Grand Total in ₹', max_digits=14)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('prepared', 'Prepared'), ('sent', 'Sent to Client'), ('under_discussion', 'Under Discussion / Revision'), ('approved', 'Approved / Accepted'), ('rejected', 'Rejected')], default='draft', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='crm.lead')),
            ],
            options={
                'verbose_name': 'Estimate / Proposal',
                'verbose_name_plural': 'Estimates & Proposals',
                'ordering': ['-estimate_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('created', 'Lead Created'), ('assigned', 'Staff Assigned'), ('status_changed', 'Status Updated'), ('followup_added', 'Follow-up Added'), ('followup_completed', 'Follow-up Completed'), ('sitevisit_scheduled', 'Site Visit Scheduled'), ('sitevisit_completed', 'Site Visit Completed'), ('estimate_created', 'Estimate Created'), ('proposal_sent', 'Proposal Sent'), ('marked_won', 'Marked Won'), ('marked_lost', 'Marked Lost'), ('note_added', 'Note Added'), ('restored', 'Lead Restored')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.lead')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead Activity',
                'verbose_name_plural': 'Lead Activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='crm.lead')),
            ],
            options={
                'verbose_name': 'Lead Note',
                'verbose_name_plural': 'Lead Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_address', models.CharField(max_length=255)),
                ('visit_date', models.DateField()),
                ('visit_time', models.TimeField(blank=True, null=True)),
                ('site_contact', models.CharField(blank=True, help_text='On-site contact person & phone', max_length=150)),
                ('property_type', models.CharField(blank=True, max_length=100)),
                ('site_condition', models.TextField(blank=True, help_text='Existing structure age, dampness, structural cracks, access roads')),
                ('requirements', models.TextField(blank=True, help_text='Client specific requirements gathered on-site')),
                ('measurements', models.TextField(blank=True, help_text='Field dimensions, built-up area check, column spans')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_site_visits', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_visits', to='crm.lead')),
            ],
            options={
                'verbose_name': 'Site Visit',
                'verbose_name_plural': 'Site Visits',
                'ordering': ['-visit_date', '-visit_time'],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', 'priority'], name='crm_lead_status_317d75_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['city', 'service_category'], name='crm_lead_city_bff327_idx'),
        ),
    ]
